// Code generated by github.com/DIMO-Network/pkg/ruptela/codegen DO NOT EDIT.
package ruptela

import (
	"fmt"
	"slices"
	"strconv"
)

const bitsInByte = 8

// Convert100 converts the given raw value to a float64.
// Unit: 'L/h' Min: '0' Max: '64255'.
func Convert100(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.05)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 64255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert101 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '255'.
func Convert101(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(-125)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert102 converts the given raw value to a float64.
// Unit: 'km' Min: '0' Max: '65535'.
func Convert102(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65535 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert103 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '255'.
func Convert103(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.39215686274509803)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert107 converts the given raw value to a float64.
// Min: '0' Max: '65535'.
func Convert107(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65535 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert108 converts the given raw value to a float64.
// Unit: '-' Min: '0'.
func Convert108(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert109 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '255'.
func Convert109(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert114 converts the given raw value to a float64.
// Unit: 'm' Min: '0' Max: '4211081215'.
func Convert114(rawValue string) (float64, error) {
	const byteSize = 4
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(5)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is within the error range.
	if 4261412864 <= rawInt && rawInt <= 4278190079 {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 4211081215 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert1148 converts the given raw value to a float64.
// Unit: 'liters' Min: '0' Max: '254'.
func Convert1148(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 254 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert1149 converts the given raw value to a float64.
// Unit: 'liters' Min: '0' Max: '254'.
func Convert1149(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 254 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert115 converts the given raw value to a float64.
// Unit: '°C' Min: '0' Max: '250'.
func Convert115(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(-40)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert1150 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '250'.
func Convert1150(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.4)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{251}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert116 converts the given raw value to a float64.
// Unit: 'L/h' Min: '0' Max: '64255'.
func Convert116(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.05)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is within the error range.
	if 65024 <= rawInt && rawInt <= 65279 {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 64255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert1187 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '250'.
func Convert1187(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.4)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{251}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert1190 converts the given raw value to a float64.
// Unit: 'kW' Min: '0' Max: '4294967294'.
func Convert1190(rawValue string) (float64, error) {
	const byteSize = 4
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.001)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{4294967295}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 4294967294 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert1191 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '1'.
func Convert1191(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 1 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert197 converts the given raw value to a float64.
// Unit: 'RPM' Min: '0' Max: '64255'.
func Convert197(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.125)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is within the error range.
	if 65024 <= rawInt && rawInt <= 65279 {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 64255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert201 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '250'.
func Convert201(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.4)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert205 converts the given raw value to a float64.
// Unit: 'l' Min: '0' Max: '65535'.
func Convert205(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65535 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert206 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '250'.
func Convert206(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.4)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert207 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '250'.
func Convert207(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.4)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert208 converts the given raw value to a float64.
// Unit: 'l' Min: '0' Max: '4211081215'.
func Convert208(rawValue string) (float64, error) {
	const byteSize = 4
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.5)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is within the error range.
	if 4261412864 <= rawInt && rawInt <= 4278190079 {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 4211081215 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert210 converts the given raw value to a float64.
// Unit: 'km/h' Min: '0' Max: '64255'.
func Convert210(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.00390625)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is within the error range.
	if 65024 <= rawInt && rawInt <= 65279 {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 64255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert29 converts the given raw value to a float64.
// Unit: 'mV' Min: '0' Max: '65535'.
func Convert29(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65535 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert313 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '7'.
func Convert313(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 7 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert316 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '7'.
func Convert316(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 7 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert347 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '7'.
func Convert347(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 7 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert35 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '1'.
func Convert35(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{2, 3}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 1 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert355 converts the given raw value to a float64.
// Unit: 'kPa' Min: '0' Max: '250'.
func Convert355(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(8)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert356 converts the given raw value to a float64.
// Unit: 'kPa' Min: '0' Max: '250'.
func Convert356(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(8)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert357 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '250'.
func Convert357(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.4)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert359 converts the given raw value to a float64.
// Unit: '-' Min: '0'.
func Convert359(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert36 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '1'.
func Convert36(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{2, 3}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 1 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert360 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '250'.
func Convert360(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(-125)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert362 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '1'.
func Convert362(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{2, 3}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 1 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert366 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '251'.
func Convert366(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(-125)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 251 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert367 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '251'.
func Convert367(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(-125)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 251 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert38 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '5'.
func Convert38(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{31}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 5 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert39 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '125'.
func Convert39(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 125 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert405 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '1'.
func Convert405(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 1 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert409 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '1'.
func Convert409(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 1 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert482 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '250'.
func Convert482(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.4)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert483 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '250'.
func Convert483(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert515 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '255'.
func Convert515(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.5)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert516 converts the given raw value to a float64.
// Unit: 'km' Min: '0' Max: '65535'.
func Convert516(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65535 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert517 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '255'.
func Convert517(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert518 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '255'.
func Convert518(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert519 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '250'.
func Convert519(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(-125)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{254}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 250 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert520 converts the given raw value to a float64.
// Unit: 'min' Min: '-2147483648' Max: '2147483647'.
func Convert520(rawValue string) (float64, error) {
	const byteSize = 4
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseInt(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse int: %w", err)
	}
	// Check if the value is less than the minimum value.
	if rawInt < -2147483648 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 2147483647 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert522 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '1'.
func Convert522(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 1 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert53 converts the given raw value to a float64.
// Unit: 'kg' Min: '0' Max: '64255'.
func Convert53(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.5)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is within the error range.
	if 65024 <= rawInt && rawInt <= 65279 {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 64255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert538 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '255'.
func Convert538(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert54 converts the given raw value to a float64.
// Unit: 'kg' Min: '0' Max: '64255'.
func Convert54(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.5)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is within the error range.
	if 65024 <= rawInt && rawInt <= 65279 {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 64255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert55 converts the given raw value to a float64.
// Unit: 'kg' Min: '0' Max: '64255'.
func Convert55(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.5)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is within the error range.
	if 65024 <= rawInt && rawInt <= 65279 {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 64255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert642 converts the given raw value to a float64.
// Unit: 'l' Min: '0' Max: '0xFFFF or 65535'.
func Convert642(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65535 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert645 converts the given raw value to a float64.
// Unit: 'km' Min: '0' Max: '0xFFFFFFFF'.
func Convert645(rawValue string) (float64, error) {
	const byteSize = 4
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{4294967295}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 4294967295 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert720 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '255'.
func Convert720(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.5)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert722 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '255'.
func Convert722(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert723 converts the given raw value to a float64.
// Unit: 'km' Min: '0' Max: '65535'.
func Convert723(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65535 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert727 converts the given raw value to a float64.
// Unit: '°C' Min: '0' Max: '0xFFFF'.
func Convert727(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(-273)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.03125)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65535 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert728 converts the given raw value to a float64.
// Unit: 'kPa' Min: '0' Max: '0xFF'.
func Convert728(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(4)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert88 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '1'.
func Convert88(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 1 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert89 converts the given raw value to a float64.
// Unit: '°C' Min: '0' Max: '64255'.
func Convert89(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(-273)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.03125)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is within the error range.
	if 65024 <= rawInt && rawInt <= 65279 {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 64255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert92 converts the given raw value to a float64.
// Unit: 'l' Min: '0' Max: '4211081215'.
func Convert92(rawValue string) (float64, error) {
	const byteSize = 4
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.001)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is within the error range.
	if 4261412864 <= rawInt && rawInt <= 4278190079 {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 4211081215 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert94 converts the given raw value to a float64.
// Unit: 'RPM' Min: '0' Max: '65,535'.
func Convert94(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.25)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65535 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert95 converts the given raw value to a float64.
// Unit: 'km/h' Min: '0' Max: '255'.
func Convert95(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert950 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '10000'.
func Convert950(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.01)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 10000 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert96 converts the given raw value to a float64.
// Unit: '°C' Min: '0' Max: '255'.
func Convert96(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(-40)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert960 converts the given raw value to a float64.
// Unit: 'PSI' Min: '0' Max: '65534'.
func Convert960(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.05)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65534 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert961 converts the given raw value to a float64.
// Unit: 'PSI' Min: '0' Max: '65534'.
func Convert961(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.05)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65534 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert962 converts the given raw value to a float64.
// Unit: 'PSI' Min: '0' Max: '65534'.
func Convert962(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.05)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65534 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert963 converts the given raw value to a float64.
// Unit: 'PSI' Min: '0' Max: '65534'.
func Convert963(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.05)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65534 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert964 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '254'.
func Convert964(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 254 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert965 converts the given raw value to a float64.
// Unit: 'PSI' Min: '0' Max: '65534'.
func Convert965(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65534 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert966 converts the given raw value to a float64.
// Unit: 'PSI' Min: '0' Max: '65534'.
func Convert966(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65534 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert967 converts the given raw value to a float64.
// Unit: 'PSI' Min: '0' Max: '65534'.
func Convert967(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65534 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert968 converts the given raw value to a float64.
// Unit: 'PSI' Min: '0' Max: '65534'.
func Convert968(rawValue string) (float64, error) {
	const byteSize = 2
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{65535}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 65534 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert97 converts the given raw value to a float64.
// Unit: '°C' Min: '0' Max: '255'.
func Convert97(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(-40)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert98 converts the given raw value to a float64.
// Unit: '%' Min: '0' Max: '255'.
func Convert98(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(0.39215686274509803)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is in the error set.
	if slices.Contains([]uint64{255}, rawInt) {
		return 0, errNotFound
	}
	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 255 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert985 converts the given raw value to a float64.
// Unit: '-' Min: '0' Max: '1'.
func Convert985(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	// Check if the value is less than the minimum value.
	if rawInt < 0 {
		return 0, errNotFound
	}
	// Check if the value is greater than the maximum value.
	if rawInt > 1 {
		return 0, errNotFound
	}
	return float64(rawInt)*multiplier + offset, nil
}

// Convert99 converts the given raw value to a float64.
// Unit: '-'.
func Convert99(rawValue string) (float64, error) {
	const byteSize = 1
	const offset = float64(0)
	const maxSize = 1<<(byteSize*bitsInByte) - 1
	const multiplier = float64(1)
	rawInt, err := strconv.ParseUint(rawValue, 16, 64)
	if err != nil {
		return 0, fmt.Errorf("could not parse uint: %w", err)
	}

	// Check if the value is equal to the maximum value for the given size.
	if rawInt == maxSize {
		return 0, errNotFound
	}

	return float64(rawInt)*multiplier + offset, nil
}
