version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - funlen
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    funlen:
      lines: 100
      statements: 50
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
      ignore-rules:
        - artefact
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    revive:
      confidence: 0
      rules:
        - name: var-declaration
        - name: package-comments
        - name: dot-imports
        - name: blank-imports
        - name: var-naming
        - name: indent-error-flow
        - name: range
        - name: errorf
        - name: error-naming
        - name: error-strings
        - name: receiver-naming
        - name: increment-decrement
        - name: error-return
        - name: unexported-return
        - name: time-naming
        - name: context-keys-type
        - name: context-as-argument
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
        path: convert-funcs_test\.go
      - linters:
          - dupl
          - errcheck
          - funlen
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
