name: generate files
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  golangci:
    runs-on: ubuntu-latest

    name: lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Checkout code
        uses: actions/checkout@v4

      - name: go mod tidy
        run: go mod tidy

      - name: go mod verify
        run: go mod verify

      - name: generate
        run: make generate

      - name: porcelain
        shell: bash
        run: |
          dirty_files="$(git status --porcelain)"
          if [[ `git status --porcelain` ]]; then
            echo "The following files are dirty after running generators:"
            echo "${dirty_files}"
            exit 1
          fi