name: golangci-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  golangci:
    runs-on: ubuntu-latest

    name: lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Checkout code
        uses: actions/checkout@v4

      - name: install golangci-lint
        run: make tools-golangci-lint
      
      - name: Run golangci-lint
        run: make lint