name: golangci-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

env:
  GOPRIVATE: github.com/DIMO-Network
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  golangci:
    runs-on: ubuntu-latest

    name: lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Checkout code
        uses: actions/checkout@v4

      - name: install golangci-lint
        uses: make tools-golangci-lint
      
      - name: Run golangci-lint
        run: make lint